#!/usr/bin/env bash

targetdir="${1:-.}"
while read filepath
do
  sed -i '' 's/1/2/g' "${filepath}"
  filedir="${filepath%/*}"
  new_filename="${filepath##*/}"
  new_filename="${new_filename/1/2}"
  new_filepath="${filedir}/${new_filename}"
  if [ "${new_filepath}" != "${filepath}" ]
  then
    mv "${filepath}" "${new_filepath}"
  fi
done < <(find "${targetdir}" -type f \( -name '*.java' -or -name '*.gradle' \) )

